version: "3.8"

services:

  mongodb:
    image: mongo
    container_name: mongodb
    env_file: ./.env
    ports:
      - $DB_LOCAL_PORT:$DB_LOCAL_PORT
    volumes:
      - db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file: ./.env
    ports:
      - $DB_UI_LOCAL_PORT:$DB_UI_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb

  app:
    depends_on:
      - mongodb # Must -> Same as the `db` service name, as declared above.
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    stdin_open: true
    tty: true
    environment:
      - MONGO_URI=$MONGO_URI_WHEN_USING_DOCKER_COMPOSE


volumes:
  db-data: {}


#------------------------------------
# If you want to rename this network:

#networks:
#  default:
#    name: YOUR-NETWORK-NAME
